host: "192.168.2.106"
port: 8848
scheme: "http"
namespace: "c5ed7cca-21ca-43dd-81ac-6a5c4689c993"
dataId: "goods-srv"
group: "dev"

#server:
#  host: "192.168.2.106"
#  port: 8082
#  name: "goods_srv"
#
#mysql:
#  host: "192.168.2.106"
#  port: 23306
#  dbName: "mxshop_goods"
#  username: "root"
#  password: "123456"
#
#consul:
#  host: "192.168.2.106"
#  port: 8500
#  name: "goods_srv"
#  tag:
#    - "goods"
#    - "go"
