host: "192.168.2.105"
port: 8080
name: "user_srv"

mysql:
  host: "192.168.2.105"
  port: 23306
  dbName: "mxshop"
  username: "root"
  password: "123456"

consul:
  host: "192.168.2.105"
  port: 8500
  name: "user_srv"
  tag:
    - "srv"
    - "go"
