nacos:
  host: "192.168.2.106"
  port: 8848
  scheme: "http"
  namespace: "09d89590-bb9a-4218-8b67-db9ac8364bba"
  dataId: "user-srv"
  group: "dev"

#server:
#  host: "192.168.2.106"
#  port: 8080
#  name: "user_srv"
#
#mysql:
#  host: "192.168.2.106"
#  port: 23306
#  dbName: "mxshop"
#  username: "root"
#  password: "123456"
#
#consul:
#  host: "192.168.2.106"
#  port: 8500
#  name: "user_srv"
#  tag:
#    - "srv"
#    - "go"
